image: alpine/edge
packages:
  - janet
sources:
  - https://git.sr.ht/~skuzzymiglet/typeup
tasks:
  - janet-setup: |
      cd janet
      sudo jpm deps
  - janet-test: |
      janet janet/test/test.janet
