image: alpine/edge
packages:
  - janet
sources:
  - https://git.sr.ht/~skuzzymiglet/typeup
tasks:
  - janet-setup: |
      cd typeup/janet
      sudo jpm deps
  - janet-test: |
      janet typeup/janet/test/test.janet
